-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDQkOzA96iBmTdRKz
C4xXdjaGUxw6f/zLnPV9J5xQnlWgCgYIKoZIzj0DAQehRANCAASIabhmkWF2Wial
+ObDn34/8GBHOuOG8Mrctzpyw7Adh32/ZDr0AAD2mr+UhsuB5Je+pg6V2DMo9cNN
BKHUzjXJ
-----END PRIVATE KEY-----